import cv2
import numpy as np
import os
from PIL import Image, ImageDraw, ImageFont

class VisualBoundingBoxAnnotator:
    """
    Visual Bounding Box Annotator for Packaging Compliance Inspection.
    Annotates packaging images with:
      - Green Bounding Boxes for compliant mandatory fields
      - Red Bounding Boxes for non-compliant / illegal / missing fields
      - Yellow Bounding Boxes for warnings / advisory rules
      - Text labels with Field Name, Status, and Rule ID
    """
    def __init__(self):
        # Color schemes (RGB for PIL)
        self.COLOR_PASS = (40, 167, 69)     # Green
        self.COLOR_FAIL = (220, 53, 69)     # Red
        self.COLOR_WARN = (255, 193, 7)     # Yellow
        self.COLOR_TEXT_BG_PASS = (212, 237, 218)
        self.COLOR_TEXT_BG_FAIL = (248, 215, 218)

    def annotate(self, image_input, audit_report, output_path):
        """
        Renders bounding boxes and compliance overlays onto packaging image.
        
        Args:
            image_input: NumPy array (BGR OpenCV image) or PIL Image object or image path string
            audit_report: Dict generated by PackagingComplianceInspector
            output_path: Filepath where annotated image will be saved
        """
        if isinstance(image_input, str):
            pil_img = Image.open(image_input).convert("RGB")
        elif isinstance(image_input, np.ndarray):
            # Convert BGR OpenCV image to RGB PIL Image
            rgb = cv2.cvtColor(image_input, cv2.COLOR_BGR2RGB)
            pil_img = Image.fromarray(rgb)
        elif isinstance(image_input, Image.Image):
            pil_img = image_input.copy()
        else:
            raise ValueError("Unsupported image_input type")

        w, h = pil_img.size
        draw = ImageDraw.Draw(pil_img)

        # Fonts
        try:
            font_title = ImageFont.truetype("arialbd.ttf", 24)
            font_label = ImageFont.truetype("arialbd.ttf", 16)
            font_sub = ImageFont.truetype("arial.ttf", 14)
        except Exception:
            font_title = font_label = font_sub = ImageFont.load_default()

        # 1. Render Top Header Banner (Inspection Summary)
        score = audit_report.get("compliance_score", 0.0)
        status = audit_report.get("status", "NON_COMPLIANT")
        header_color = self.COLOR_PASS if status == "COMPLIANT" else self.COLOR_FAIL
        
        draw.rectangle([0, 0, w, 65], fill=header_color)
        banner_text = f"LEGAL METROLOGY COMPLIANCE AUDIT: [{status}] - Score: {score}%"
        sub_banner = f"Violations: {audit_report['violations_count']} | Passed: {audit_report['passed_count']} | Warnings: {audit_report['warnings_count']}"
        
        draw.text((20, 12), banner_text, fill=(255, 255, 255), font=font_title)
        draw.text((20, 42), sub_banner, fill=(240, 240, 240), font=font_sub)

        # Map bounding box coordinates from normalized 0-1000 scale to pixel coordinates
        def denorm_bbox(bbox):
            ymin, xmin, ymax, xmax = bbox
            y1 = int((ymin / 1000.0) * h)
            x1 = int((xmin / 1000.0) * w)
            y2 = int((ymax / 1000.0) * h)
            x2 = int((xmax / 1000.0) * w)
            return [x1, y1, x2, y2]

        # 2. Draw Passed Bounding Boxes (GREEN)
        for check in audit_report.get("passed_checks", []):
            bbox = check.get("bbox")
            if bbox and bbox != [0, 0, 0, 0]:
                x1, y1, x2, y2 = denorm_bbox(bbox)
                # Expand box slightly for padding
                x1, y1 = max(5, x1 - 5), max(70, y1 - 5)
                x2, y2 = min(w - 5, x2 + 5), min(h - 5, y2 + 5)

                draw.rectangle([x1, y1, x2, y2], outline=self.COLOR_PASS, width=4)
                
                # Draw text badge above box
                badge_str = f"[PASS] {check['field']}"
                draw.rectangle([x1, max(70, y1 - 22), x1 + len(badge_str) * 9, max(70, y1)], fill=self.COLOR_PASS)
                draw.text((x1 + 4, max(70, y1 - 20)), badge_str, fill=(255, 255, 255), font=font_sub)

        # 3. Draw Violation Bounding Boxes (RED)
        for viol in audit_report.get("violations", []):
            bbox = viol.get("bbox")
            field_name = viol.get("field", "Field")
            issue = viol.get("issue", "")
            rule_id = viol.get("rule_id", "RULE")

            if bbox and bbox != [0, 0, 0, 0]:
                x1, y1, x2, y2 = denorm_bbox(bbox)
                x1, y1 = max(5, x1 - 6), max(70, y1 - 6)
                x2, y2 = min(w - 5, x2 + 6), min(h - 5, y2 + 6)

                draw.rectangle([x1, y1, x2, y2], outline=self.COLOR_FAIL, width=5)

                # Draw violation label box
                badge_str = f"[FAIL - {rule_id}] {field_name}"
                draw.rectangle([x1, max(70, y1 - 25), x1 + len(badge_str) * 9 + 10, max(70, y1)], fill=self.COLOR_FAIL)
                draw.text((x1 + 4, max(70, y1 - 22)), badge_str, fill=(255, 255, 255), font=font_label)
            else:
                # Missing field notice banner placed at top right
                missing_str = f"[MISSING - {rule_id}] {field_name}: {issue}"
                draw.rectangle([w - 450, 75 + len(audit_report['violations']) * 35, w - 10, 105 + len(audit_report['violations']) * 35], fill=self.COLOR_FAIL)
                draw.text((w - 440, 80 + len(audit_report['violations']) * 35), missing_str[:55], fill=(255, 255, 255), font=font_sub)

        # Save output image
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        pil_img.save(output_path)
        print(f"[ANNOTATOR] Saved annotated inspection output to: {output_path}")
        return output_path
