import React, { useEffect, useState } from "react";
import { fetchReportsApi, triggerPdfDownload } from "../services/apiClient";
import {
  FileText,
  Search,
  Download,
  CheckCircle2,
  AlertOctagon,
  Calendar,
  Building,
  RefreshCw,
  ExternalLink
} from "lucide-react";

interface NoticeReport {
  notice_number: string;
  notice_type: string;
  pdf_filename: string;
  pdf_url: string;
  issued_at: string;
  status: string;
  inspection_id?: string;
  product_name?: string;
  company_name?: string;
}

export const ReportsPage: React.FC = () => {
  const [reports, setReports] = useState<NoticeReport[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [searchTerm, setSearchTerm] = useState<string>("");

  const loadReports = async () => {
    setLoading(true);
    try {
      const data = await fetchReportsApi();
      setReports(data);
    } catch (err) {
      console.error("Failed to load reports", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const filtered = reports.filter((r) => {
    const nNum = r.notice_number || "";
    const pName = r.product_name || "";
    const cName = r.company_name || "";
    const matches =
      nNum.toLowerCase().includes(searchTerm.toLowerCase()) ||
      pName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      cName.toLowerCase().includes(searchTerm.toLowerCase());
    return matches;
  });

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-purple-950 to-slate-900 text-white rounded-2xl p-8 border border-purple-500/20 shadow-xl relative overflow-hidden">
        <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <div className="flex items-center gap-2 text-purple-400 font-semibold tracking-wider text-xs uppercase mb-2">
              <FileText className="w-4 h-4" /> Official Court-Ready Archive
            </div>
            <h1 className="text-3xl font-extrabold text-white tracking-tight">
              Legal Notice & Compliance Certificate Archive
            </h1>
            <p className="text-slate-300 text-sm mt-1 max-w-2xl">
              Compiled statutory Show-Cause Notices and Compliance Certificates generated by ReportLab engine in accordance with Legal Metrology Act, 2009.
            </p>
          </div>
          <button
            onClick={loadReports}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2.5 bg-purple-600 hover:bg-purple-500 text-white font-medium rounded-xl transition-all shadow-md active:scale-95 disabled:opacity-50"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
            Refresh Archive
          </button>
        </div>
      </div>

      {/* Search */}
      <div className="flex justify-between items-center bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <div className="relative w-full md:w-96">
          <Search className="w-4 h-4 absolute left-3 top-3.5 text-slate-400" />
          <input
            type="text"
            placeholder="Search notice number, product, or company..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-4 py-2 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 dark:text-white"
          />
        </div>
        <div className="text-xs font-semibold text-slate-500">
          Showing {filtered.length} of {reports.length} generated notices
        </div>
      </div>

      {/* Table */}
      {loading ? (
        <div className="bg-white dark:bg-slate-900 rounded-xl p-8 space-y-4 animate-pulse border border-slate-200 dark:border-slate-800">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-12 bg-slate-100 dark:bg-slate-800 rounded-lg" />
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <div className="bg-white dark:bg-slate-900 rounded-xl p-12 text-center border border-slate-200 dark:border-slate-800">
          <FileText className="w-12 h-12 text-slate-400 mx-auto mb-3" />
          <h3 className="text-lg font-bold text-slate-900 dark:text-white">No Legal Notices Archived</h3>
          <p className="text-sm text-slate-500 mt-1">Execute an inspection to auto-generate formal court-ready PDF documents.</p>
        </div>
      ) : (
        <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 dark:bg-slate-800/80 border-b border-slate-200 dark:border-slate-800 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                  <th className="p-4">Notice Reference Number</th>
                  <th className="p-4">Document Classification</th>
                  <th className="p-4">Associated Commodity / Entity</th>
                  <th className="p-4">Issuance Date</th>
                  <th className="p-4 text-right">PDF Download</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 dark:divide-slate-800 text-sm">
                {filtered.map((item, idx) => (
                  <tr key={idx} className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                    <td className="p-4 font-mono font-bold text-purple-600 dark:text-purple-400 text-xs">
                      {item.notice_number}
                    </td>

                    <td className="p-4">
                      {item.notice_type === "COMPLIANCE_CERTIFICATE" ? (
                        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 bg-emerald-100 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 font-bold text-xs rounded-full">
                          <CheckCircle2 className="w-3.5 h-3.5" /> Compliance Certificate
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 bg-rose-100 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300 font-bold text-xs rounded-full">
                          <AlertOctagon className="w-3.5 h-3.5" /> Show-Cause Notice
                        </span>
                      )}
                    </td>

                    <td className="p-4">
                      <div className="font-bold text-slate-900 dark:text-white">
                        {item.product_name || "Pre-Packaged Commodity"}
                      </div>
                      <div className="text-xs text-slate-500 flex items-center gap-1 mt-0.5">
                        <Building className="w-3 h-3" />
                        {item.company_name || "Offending Enterprise"}
                      </div>
                    </td>

                    <td className="p-4 text-xs text-slate-500">
                      <div className="flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5" />
                        {item.issued_at ? new Date(item.issued_at).toLocaleString() : "Recent"}
                      </div>
                    </td>

                    <td className="p-4 text-right">
                      <button
                        onClick={() => triggerPdfDownload(item.pdf_url)}
                        className="px-3.5 py-1.5 bg-purple-600 hover:bg-purple-500 text-white font-semibold text-xs rounded-lg transition-colors inline-flex items-center gap-1.5 shadow-sm active:scale-95 cursor-pointer"
                      >
                        <Download className="w-3.5 h-3.5" /> Download PDF <ExternalLink className="w-3 h-3" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
};
